DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS program CASCADE;
DROP TABLE IF EXISTS college CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(30) UNIQUE NOT NULL,
	email VARCHAR(60) UNIQUE NOT NULL,
	user_password VARCHAR(60) NOT NULL	
);


CREATE TABLE IF NOT EXISTS college (
	code VARCHAR(25) PRIMARY KEY,
	name VARCHAR(400) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS program (
	code VARCHAR(25) PRIMARY KEY,
	name VARCHAR(400) UNIQUE NOT NULL,
	college_code VARCHAR(25),
	FOREIGN KEY (college_code) 
		REFERENCES college(code)
		ON DELETE SET NULL 
		ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS students (
	id VARCHAR(9) PRIMARY KEY,
	first_name VARCHAR(200) NOT NULL,
	last_name VARCHAR(200),
	gender VARCHAR(50),
	year_level VARCHAR(10) NOT NULL,
	course_code VARCHAR(25),
	FOREIGN KEY (course_code) 
		REFERENCES program(code)
		ON DELETE SET NULL
		ON UPDATE CASCADE
	
);